AWSTemplateFormatVersion: "2010-09-09"
Description: "Secure S3 Bucket with Security Enforcement"

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    AllowedPattern: "^[a-z0-9.-]{3,63}$"

Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:

      BucketName: !Ref BucketName

      VersioningConfiguration:
        Status: Enabled

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

          #Deny any request that is NOT using HTTPS (TLS)
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*
            Condition:
              Bool:
                aws:SecureTransport: false

          #Deny uploads that are NOT encrypted
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256

Outputs:
  BucketNameOutput:
    Description: "Name of the S3 bucket"
    Value: !Ref SecureBucket

  BucketArnOutput:
    Description: "ARN of the S3 bucket"
    Value: !GetAtt SecureBucket.Arn
